export * from "./agencias/index.js";
export * from "./cuenta/index.js";
export * from "./elecciones/index.js";
export * from "./inscripciones/index.js";
export * from "./recovery/index.js";
export * from "./representantes/index.js";
export * from "./socios/index.js";
export * from "./votos/index.js";
export * from "./justificacion/index.js";
